admin/views.py
from .forms import roleForm,SelectionForm,groupuserForm
import db
from core.forms import laborcontractForm,forexsalaryForm
from employee.forms import Employeeinformation
from flask_login import current_user,login_user,login_required,logout_user
from flask import Blueprint, flash, redirect, render_template, request, url_for,session, send_file,send_from_directory,make_response,Response
import pandas as pd
from tkinter import Tk, filedialog
from flask_mail import Message
from io import BytesIO
import json
import pyotp
from validation.forms import informationUserForm
from core.models import informationUserJob
from __init__ import file_path_default,mail,app
import pdfkit
from io import BytesIO
import zipfile
admin = Blueprint("admin", __name__)
_role_user = ""
_roleadmin = "admin"
_image_path_admin = ""
_fullname_admin = ""
@admin.route('/adminpage/<image_path_admin>/<fullname_admin>')
@login_required
def adminpage(image_path_admin, fullname_admin):
    global _image_path_admin,_fullname_admin
    _image_path_admin=image_path_admin
    _fullname_admin = fullname_admin
    print("admin fullname is " + _fullname_admin)
    return render_template("admin/adminpage.html",image_path_admin=_image_path_admin,roleuser=_role_user,roleadmin = _roleadmin,fullname_admin=fullname_admin)

@admin.route('/adminpage/roles',methods=["GET", "POST"])
def displayRoles():
    global _image_path_admin,_fullname_admin
    conn=db.connection()
    cursor=conn.cursor()
    sql="select * from role_user"
    cursor.execute(sql)
    role_user=cursor.fetchall()
    conn.commit()
    conn.close()
    form=roleForm(request.form)
    if form.validate_on_submit():
        conn=db.connection()
        cursor=conn.cursor()
        sql="insert into role_user values(?)"
        value=(form.role.data)
        cursor.execute(sql,value)
        conn.commit()
        conn.close()
        return redirect(url_for("admin.displayRoles"))
    role_names = [(role[0],role[1]) for role in role_user]
    return render_template("admin/manageRole.html",data=role_names,form=form,image_path_admin=_image_path_admin,roleadmin=_roleadmin,fullname_admin =  _fullname_admin,roleuser=session.get('roleuser'))

@admin.route("/adminpage/updatepage/<idrole>",methods=["GET", "POST"])
def rolepage(idrole):
    global _image_path_admin,_fullname_admin
    conn=db.connection()
    cursor=conn.cursor()
    sql="select role_name from role_user where id=?"
    value=(idrole)
    cursor.execute(sql,value)
    rolename=cursor.fetchone()
    conn.commit()
    conn.close()
    if request.method=="POST":
        conn=db.connection()
        cursor=conn.cursor()
        sql="update role_user set role_name=? where id=?"
        value=(request.form["user_role"],idrole)
        cursor.execute(sql,value)
        conn.commit()
        conn.close()
        return redirect(url_for("admin.displayRoles"))
    return render_template("admin/updatepagerole.html",rolename=rolename[0],idrole=idrole,image_path_admin=_image_path_admin,roleadmin=_roleadmin,fullname_admin =  _fullname_admin,roleuser=session.get('roleuser'))
@admin.route("/adminpage/deleterole/<idrole>")
def deleterole(idrole):
    conn=db.connection()
    cursor=conn.cursor()
    sql="""SET NOCOUNT ON;
            EXEC deleteRole @role_id=?"""
    value=(idrole)
    cursor.execute(sql,value)
    conn.commit()
    conn.close()
    return redirect(url_for("admin.displayRoles"))

@admin.route("/adminpage/usersmanager",methods=["GET", "POST"])
def displayusers():  
    #list account
    global _image_path_admin,_fullname_admin
    totp=pyotp.TOTP('adminroles')
    totp=totp.now()
    session['is_admin']=str(totp)
    session['rolegroup']='admin'
    _roleadmin = "admin"
    conn=db.connection()
    cursor=conn.cursor()
    sql="select u.id, i.email,r.role_name ,u.is_active,i.id from informationUser i join user_account u on i.id_useraccount=u.id join role_user r on r.id= u.role_id where u.role_id is not null"
    cursor.execute(sql)
    users=cursor.fetchall()
    conn.commit()
    conn.close()
    usersrole=[(user[0],user[1],user[2],user[3]) for user in users]
    #list of blocked users
    conn=db.connection()
    cursor=conn.cursor()
    sql="select u.id, i.email,r.role_name ,u.is_active,i.id from informationUser i join user_account u on i.id_useraccount=u.id join role_user r on r.id= u.role_id where u.is_active=0"
    cursor.execute(sql)
    users=cursor.fetchall()
    conn.commit()
    conn.close()
    usersblock=[(user[0],user[1],user[2],user[3]) for user in users]

    roles=[]
    roles.append('ALL')
    conn=db.connection()
    cursor=conn.cursor()
    sql="select * from role_user "
    cursor.execute(sql)
    roles_temp=cursor.fetchall()
    for type in roles_temp:
        roles.append(type[1])
    #roles=[role[1] for role in roles_temp]
    conn.commit()
    conn.close()
   
    table='ALL'
    #load all user 
    conn=db.connection()
    cursor=conn.cursor()
    sql="select i.*,r.role_name,i.id from informationUser i join user_account u on i.id_useraccount=u.id join role_user r on u.role_id=r.id"
    cursor.execute(sql)
    users=cursor.fetchall()
    conn.commit()
    conn.close()
    Alluser=[(user[0],user[1],user[2],user[3],user[4],user[6],user[7],user[8],user[9],user[10],user[11],user[12],user[13]) for user in users]
     
    selecttionitem=[]
    session['selectionItem']=selecttionitem
    
    if request.method=='POST' and request.form.get('fillter')=='fillter':
        table=request.form['roletype']
        if table=='candidate':
            session['table']='candidate'
            roles.remove('candidate')
            roles.insert(0, 'candidate')
            conn=db.connection()
            cursor=conn.cursor()
            sql="select i.*,r.role_name from informationUser i  join user_account u on i.id_useraccount=u.id join role_user r on u.role_id=r.id where r.role_name='candidate'"
            cursor.execute(sql)
            users=cursor.fetchall()
            conn.commit()
            conn.close()
            Alluser=[(user[0],user[1],user[2],user[3],user[4],user[6],user[7],user[8],user[9],user[10],user[11],user[12],user[13]) for user in users]
        elif table=='ALL':
            session['table']='ALL'
            roles.remove('ALL')
            roles.insert(0, 'ALL')
            conn=db.connection()
            cursor=conn.cursor()
            sql="select i.*,r.role_name from informationUser i join user_account u on i.id_useraccount=u.id join role_user r on u.role_id=r.id"
            cursor.execute(sql)
            users=cursor.fetchall()
            conn.commit()
            conn.close()
            Alluser=[(user[0],user[1],user[2],user[3],user[4],user[6],user[7],user[8],user[9],user[10],user[11],user[12],user[13]) for user in users]
        elif table=='employee':
            session['table']='employee'
            roles.remove('employee')
            roles.insert(0, 'employee')
            conn=db.connection()
            cursor=conn.cursor()
            sql="select i.*,r.role_name from informationUser i  join user_account u on i.id_useraccount=u.id join role_user r on u.role_id=r.id where r.role_name='employee'"
            cursor.execute(sql)
            users=cursor.fetchall()
            conn.commit()
            conn.close()
            Alluser=[(user[0],user[1],user[2],user[3],user[4],user[6],user[7],user[8],user[9],user[10],user[11],user[12],user[13]) for user in users]
    elif request.form.get('exportexcel')=='exportexcel':
        for user in Alluser:
            selecttionitem.append(request.form.get(str(user[0])))
        table=session.get('table')
        if(table==None):
            table='ALL'
        check1=is_all_null(selecttionitem)
        if check1==False:
            #return str(table)
            return redirect(url_for("admin.exportfileexcel",typerole=table))
        else:
            session['selectionItem']=[]
            return redirect(url_for("admin.exportfileexcel",typerole=table))
    elif request.form.get('exportpdf')=='exportpdf':
        for user in Alluser:
            selecttionitem.append(request.form.get(str(user[0])))
        Selecttionitem=session.get('selectionItem', [])
        table=session.get('table')
        
        if(table==None):
            table='ALL'
        check= is_all_null(Selecttionitem)
        if check==False:
            zip_buffer = BytesIO()
            with zipfile.ZipFile(zip_buffer, 'a', zipfile.ZIP_DEFLATED, False) as zip_file:
                for id in Selecttionitem:
                    if(str(id)!='None'):
                        pdf_content = exportfilepdf(str(id),table)
            
                        zip_file.writestr(f'output'+id+'.pdf', pdf_content)
            zip_buffer.seek(0)
            response = Response(zip_buffer.read())
            response.headers["Content-Disposition"] = "attachment; filename=your_zip_file_pdf.zip"
            response.headers["Content-Type"] = "application/zip"

            return response
        else:
            Selecttionitem=[]
            for user in Alluser:
                if user[12]==table :
                   Selecttionitem.append(str(user[0]))
                if table=='ALL':
                    Selecttionitem.append(str(user[0]))
            session['selectionItem']=Selecttionitem
            Selecttionitem=session.get('selectionItem', [])
            #return Selecttionitem
            #return table
            zip_buffer = BytesIO()
            with zipfile.ZipFile(zip_buffer, 'a', zipfile.ZIP_DEFLATED, False) as zip_file:
                for id in Selecttionitem:
                    if(str(id)!='None'):
                        
                        pdf_content = exportfilepdf(str(id),table)
            
                        zip_file.writestr(f'output'+id+'.pdf', pdf_content)
            zip_buffer.seek(0)
            response = Response(zip_buffer.read())
            response.headers["Content-Disposition"] = "attachment; filename=your_zip_file_pdf.zip"

templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>HRM MANGAGERMENT</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <!-- CSS only -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
  />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" crossorigin="anonymous" />

    
    
    {% block css %}{% endblock %}
  </head>
  <body>

      <!--navigation  -->
    {% include "navigation.html" %} 

    <div class="container" style="margin-top: 50px;">
      <br>
      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
           {{message}}
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        </div>
        <div class="col-md-4"></div>
      </div>
      {% endif %}
      {% endwith %}
      <!-- child template -->
      {% block content %}{% endblock %}
    </div>


    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
  </body>
</html>

templates/footer.html
<!-- Footer -->
<footer class="full_width w3-center w3-black w3-padding-64">
    <a href="#home" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
    <div class="w3-xlarge w3-section">
      <i class="fa fa-facebook-official w3-hover-opacity"></i>
      <i class="fa fa-instagram w3-hover-opacity"></i>
      <i class="fa fa-snapchat w3-hover-opacity"></i>
      <i class="fa fa-pinterest-p w3-hover-opacity"></i>
      <i class="fa fa-twitter w3-hover-opacity"></i>
      <i class="fa fa-linkedin w3-hover-opacity"></i>
    </div>
    <p>Powered by CONNEXUS</a></p>
  </footer>

templates/navigation.html
<div class="w3-top">
    <!-- navigation when user login successfully -->
    
    {%if current_user.is_authenticated and roleadmin == "admin" %}
    <div class="w3-bar w3-white w3-card" id="myNavbar" style="line-height: 2.8;font-family: Verdana,sans-serif">
        <a href="/home" class="w3-bar-item w3-button w3-wide">CONNEXUS</a>
        <div class="w3-right w3-hide-small" style="display: flex; align-items: center;">
            <!-- Chỗ này chỉ hiển thị khi người dùng chưa đăng nhập -->
            <a href="{{url_for('admin.displayRoles')}}" onclick="w3_close()" class="w3-bar-item w3-button">ROLE MANAGEMENT</a>
            <a href="{{url_for('admin.displayusers')}}" class="w3-bar-item w3-button">USER MANAGEMENT</a>
            <a href="{{url_for('admin.groupuserpage')}}" class="w3-bar-item w3-button">GROUP USER</a>
            <div class="profile-dropdown" >
                <div onclick="toggle()" id="profile-dropdown-btn" class="btn">
                    <img id="avatarImage" src="{{ url_for('static', filename='source/' + image_path_admin) }}" alt="avatar" style="border-radius: 10%; width: 40px; height: 40px;">
                    <span>{{fullname_admin }}<i class="fa-solid fa-angle-down"></i></span>
                </div> 
            </div>
        </div>
    </div>
    <div class="w3-right w3-hide-small">
        <ul class="profile-dropdown-list">
        </p>
                <p class="profile-dropdown-list-item" >
                    <a href="\userinformation\{{current_user.id}}\None">
                        <i class="fa-regular fa-user"></i>
                        Profile 
                    </a>
            </p>
            <p class="profile-dropdown-list-item">
                <a href="">
                    <i class="fa-regular fa-envelope"></i>
                    Setting
                </a>
            </p>
            <p class="profile-dropdown-list-item">
                <a href="\getcodechangepassword">
                    <i class="fa-solid fa-key"></i>
                    Change Password
                </a>
            </p>
            <hr />
            <p class="profile-dropdown-list-item">
                <a href="{{url_for('authentication.logout')}}">
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                    Log out
                </a>
            </p>
        </ul>
    </div>
</div>
{% elif current_user.is_authenticated %}
    <div>
        <div class="w3-bar w3-white w3-card" id="myNavbar" style="line-height: 2.8;font-family: Verdana,sans-serif">
            <a href="/home" class="w3-bar-item w3-button w3-wide">CONNEXUS</a>
            <div class="w3-right w3-hide-small">
                <!-- Chỗ này chỉ hiển thị khi người dùng đã đăng nhập -->
            {%if image_path %}
                <div class="profile-dropdown" >
                    <div onclick="toggle()" class="profile-dropdown-btn">
                        <img id="avatarImage" src="{{ url_for('static', filename='source/' + image_path) }}" alt="avatar" style="border-radius: 50%; width: 40px; height: 40px;">
                        <span>{{fullname }} {{current_user.getdate}}<i class="fa-solid fa-angle-down"></i></span>
                        <!-- <span>{{current_user.getdate}}</span> -->
                    </div> 
                </div>
            </div>
        </div >
        <div class="w3-right w3-hide-small">
            <ul class="profile-dropdown-list">
                </p>
                    <p class="profile-dropdown-list-item" >
                        <a href="\userinformation\{{current_user.id}}\None">
                            <i class="fa-regular fa-user"></i>
                            Profile 
                        </a>
                </p>
                <p class="profile-dropdown-list-item">
                    <a href="/extractCCCD">
                        <i class="fa-regular fa-envelope"></i>
                        Inbox
                    </a>
                </p>
                <p class="profile-dropdown-list-item">
                    <a href="\getcodechangepassword">
                        <i class="fa-solid fa-key"></i>
                        Change Password
                    </a>
                </p>
                <p class="profile-dropdown-list-item">
                    <a href="#">
                        <i class="fa-regular fa-circle-question"></i>
                        Help & Support
                    </a>
                </p>
                <hr />
                <p class="profile-dropdown-list-item">
                    <a href="{{url_for('authentication.logout')}}">
                        <i class="fa-solid fa-arrow-right-from-bracket"></i>
                        Log out
                    </a>
                </p>
            </ul>
            {%endif%}
        </div>
    </div>
    
    {% else %}
        <!-- navigation when user does not log in -->
        <div class="w3-bar w3-white w3-card" id="myNavbar" style="line-height: 2.8;font-family: Verdana,sans-serif">
            <a href="/startPage" class="w3-bar-item w3-button w3-wide">CONNEXUS</a>
            <div class="w3-right w3-hide-small">
                <!-- Chỗ này chỉ hiển thị khi người dùng chưa đăng nhập -->
                <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">ABOUT</a>
                <a href="/signin" class="w3-bar-item w3-button">SIGN IN</a>
                <a href="/register" class="w3-bar-item w3-button">REGISTER</a>
                <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button">CONTACT</a>
            </div>
        </div>
    {% endif %}
</div>
<script>
    let profileDropdownList = document.querySelector(".profile-dropdown-list");
    let btn = document.querySelector(".profile-dropdown-btn");

    let classList = profileDropdownList.classList;

    const toggle = () => classList.toggle("active");

    window.addEventListener("click", function (e) {
        if (!btn.contains(e.target)) classList.remove("active");
    });

</script>