validation/models.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Email, EqualTo, Length,InputRequired
class informationUser():
    id=0,
    Fullname="",
    Nickname="",
    Email="",
    Contactaddress="",
    id_useraccount=""
    Phone =""
    LinkedIn =""
    Years =""
    Location =""
    Maritalstatus =""
    Ethnicgroup =""
    Religion =""



    def __init__(self,id,Fullname,Nickname,Email,Contactaddress,id_useraccount,Phone,LinkedIn,Years,Location,Maritalstatus,Ethnicgroup,Religion):
        self.id=id
        self.Fullname = Fullname
        self.Nickname = Nickname
        self.Email=Email
        self.Contactaddress = Contactaddress
        self.id_useraccount = id_useraccount
        self.Phone = Phone
        self.LinkedIn = LinkedIn
        self.Years = Years
        self.Location = Location
        self.Maritalstatus = Maritalstatus
        self.Ethnicgroup = Ethnicgroup
        self.Religion = Religion

class latestEmployment():
    id=0
    Employer=""
    Jobtittle = ""
    AnnualSalary = ""
    AnnualBonus = ""
    RetentionBonus = ""
    RetentionBonusExpiredDate = ""
    StockOption = ""
    StartDate = ""
    EndDate = ""
    IdInformationUser = ""

    def __init__(self,id,Employer,Jobtittle,AnnualSalary,AnnualBonus,RetentionBonus,RetentionBonusExpiredDate,StockOption,StartDate,EndDate,IdInformationUser):
        self.id= id
        self.Employer =Employer
        self.Jobtittle =Jobtittle
        self.AnnualBonus =AnnualBonus
        self.AnnualSalary = AnnualSalary
        self.RetentionBonus =RetentionBonus
        self.RetentionBonusExpiredDate =RetentionBonusExpiredDate
        self.StockOption =StockOption
        self.StartDate =StartDate
        self.EndDate =EndDate
        self.IdInformationUser = IdInformationUser
    

class usercccd():
    No = ""
    FullName = ""
    DateOfbirth = ""
    PlaceOfBirth = ""
    Address = ""
    IssueOn = ""
    IdInformationUser = ""

    def __init__(self, No, FullName, DateOfbirth, PlaceOfBirth, Address, IssueOn, IdInformationUser):
        self.No = No
        self.FullName = FullName
        self.DateOfbirth = DateOfbirth
        self.PlaceOfBirth = PlaceOfBirth
        self.Address = Address
        self.IssueOn = IssueOn
        self.IdInformationUser = IdInformationUser

validation/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField,StringField,IntegerField,DateTimeField
from wtforms.validators import DataRequired, Email, EqualTo, Length,InputRequired, Regexp

from validation.models import informationUser


class informationUserForm(FlaskForm):
    Fullname = StringField("Fullname", validators=[InputRequired(message='Fullname is required')])
    Nickname = StringField("Nickname")
    Email = EmailField("Email", validators=[DataRequired(), Email()])
    Contactaddress = StringField("Contactaddress")
    IdUserAccount = IntegerField("IdUserAccount")
    Phone = StringField("Phone")
    LinkedIn = StringField("LinkedIn")
    Years = IntegerField("Years")
    Location = StringField("Location")
    Maritalstatus = StringField("Maritalstatus")
    Ethnicgroup = StringField("Ethnicgroup")
    Religion = StringField("Religion")

class latestEmploymentForm(FlaskForm):
    Employer = StringField("Employer", validators=[InputRequired(message='Employer name is required')])
    Jobtittle = StringField("Jobtittle")
    AnnualSalary = IntegerField("AnnualSalary")
    AnnualBonus = IntegerField("AnnualBonus")
    RetentionBonus = IntegerField("RetentionBonus")
    RetentionBonusExpiredDate = DateTimeField("RetentionBonusExpiredDate")
    StockOption = IntegerField("StockOption")
    StartDate = DateTimeField("StartDate")
    EndDate = DateTimeField("EndDate")
    IdInformationUser = IntegerField("IdInformationUser")

class usercccdForm(FlaskForm):
    No = IntegerField("No", validators=[InputRequired(message='Citizen Identification No is required')])
    FullName = StringField("Full Name", validators=[InputRequired(message='Full Name is required')])
    DateOfbirth = DateTimeField("Date Of Birth")
    PlaceOfBirth = StringField("Place Of Birth")
    Address = StringField("Address")
    IssueOn = DateTimeField("Issue On")
    IdInformationUser = IntegerField("IdInformationUser")

validation/views.py
from .forms import informationUserForm
from validation.models import informationUser
from flask import Blueprint, flash, redirect, render_template, request, url_for
from itsdangerous import URLSafeTimedSerializer
from flask_login import current_user,login_user,login_required,logout_user
import db

from flask_mail import Message

from __init__ import app,mail ,file_path_default

validate = Blueprint("validation", __name__)

@validate.route("/infomationuser", methods=["GET", "POST"])
@login_required 
def informationuser():
    form = informationUserForm(request.form)
    
    if form.validate_on_submit():
        email=""
        if current_user.authenticated_by=="normal" or current_user.authenticated_by=="google":
            email=current_user.email
        else:
            email=form.Email.data
            current_user.email=email
        
        conn=db.connection()
        cursor=conn.cursor()
        sql="select * from informationUser where id_useraccount=?"
        value=(current_user.id)
        cursor.execute(sql,value)
        user_temp=cursor.fetchone()
        conn.commit()
        conn.close()
        if user_temp is None:

            conn=db.connection()
            cursor=conn.cursor()
            sql="""SET NOCOUNT ON;
                    insert into informationUser(Fullname,Nickname,Email,Contactaddress,id_useraccount) values(?,?,?,?,?)
                    DECLARE @id int;
                    SET @id = SCOPE_IDENTITY();    
                    insert into latestEmployment(idinformationuser) values (@id)"""
            value=(form.Fullname.data,form.Nickname.data,email,form.Contactaddress.data,current_user.id)
            cursor.execute(sql,value)
            conn.commit()
            conn.close()
        token = generate_token(email)
        confirm_url = url_for("validation.confirm_email", token=token, _external=True)
        html = render_template("validation/confirm_email.html", confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(email, subject, html)
        flash("A confirmation email has been sent via email.", "success")
        return redirect(url_for("validation.inactive"))
    return render_template("validation/informationUserValidate.html",image_path=file_path_default, form=form)

@validate.route("/inactiveEmail")
@login_required
def inactive():
    if current_user.is_information_validate:
        return redirect(url_for("core.home"))
    return render_template("validation/inactiveEmail.html",image_path=file_path_default)
@login_required
def generate_token(email):
    serializer = URLSafeTimedSerializer(app.config["SECRET_KEY"])
    return serializer.dumps(email, salt=app.config["SECURITY_PASSWORD_SALT"])

@login_required
def confirm_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(app.config["SECRET_KEY"])
    try:
        email = serializer.loads(
            token, salt=app.config["SECURITY_PASSWORD_SALT"], max_age=expiration
        )
        return email
    except Exception:
        return False
    
@validate.route("/confirm/<token>")
@login_required
def confirm_email(token):
    if current_user.is_information_validate:
        conn=db.connection()
        cursor=conn.cursor()
        sql="select i.id from user_account u join informationUser i on i.id_useraccount=u.id where u.id=?"
        value=(current_user.id)
        cursor.execute(sql,value)
        userinfor=cursor.fetchone()
        conn.commit()
        conn.close()
        current_user.idinformationuser=userinfor[0]
        flash("Account already confirmed.", "success")
        return redirect(url_for("core.home"))
    email = confirm_token(token)
    conn=db.connection()
    cursor=conn.cursor()
    sql="select * from informationUser where id_useraccount=?"
    value=(current_user.id)
    cursor.execute(sql,value)
    information=cursor.fetchone()
    conn.commit()
    conn.close()
    if information[3] == email:
        current_user.is_information_validate = True
        conn=db.connection()
        cursor=conn.cursor()
        sql="update user_account set infor_validate=1 where id=?"
        value=(current_user.id)
        cursor.execute(sql,value)
        conn.commit()
        conn.close()

        conn=db.connection()
        cursor=conn.cursor()
        sql="select i.id from user_account u join informationUser i on i.id_useraccount=u.id where u.id=?"
        value=(current_user.id)
        cursor.execute(sql,value)
        userinfor=cursor.fetchone()
        conn.commit()
        conn.close()
        current_user.idinformationuser=userinfor[0]
        flash("You have confirmed your account. Thanks!", "success")
    else:
        # conn=db.connection()
        # cursor=conn.cursor()
        # sql="update informationUser where id_useraccount=?"
        # value=(current_user.id)
        # cursor.execute(sql,value)
        # conn.commit()
        # conn.close()
        flash("The confirmation link is invalid or has expired.", "danger")
        redirect(url_for("validation.informationuser"))
    if current_user.role_user == None:
        logout_user()
        flash("waiting for admin assign role")
        return redirect('/')
    return redirect(url_for("core.home"))

@validate.route("/resend")
@login_required
def resend_confirmation():
    if current_user.is_information_validate:
        flash("Your account has already been confirmed.", "success")
        return redirect(url_for("core.home"))
    token = generate_token(current_user.email)
    confirm_url = url_for("validation.confirm_email", token=token, _external=True)
    html = render_template("validation/confirm_email.html", confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash("A new confirmation email has been sent.", "success")
    return redirect(url_for("validation.inactive"))

def send_email(to, subject, template):
    msg = Message(
        subject,
        recipients=[to],
        html=template,
        sender=app.config["MAIL_DEFAULT_SENDER"],
    )
    mail.send(msg)

templates/validation/confirm_email.html
<p>
    Welcome! Thanks for signing up. Please follow this link to activate your
    account:
  </p>
  <p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
  <br />
  <p>Cheers!</p>

templates/validation/inactiveEmail.html
{% extends "_base.html" %}

{% block content %}
<body style="background-color: rgb(212, 170, 118);">
  <div class="container_announcement">
    <br />
    <p>
      A email confirmation has been sent to your email address. 
    </p>

    <p>      
      If you have not confirmed your account yet, please check your inbox (and your spam folder) 
    </p>

    <p>
      you should have received an email with a confirmation link.
    </p>
    <p>
      Did not get the email?
      <a href="{{ url_for('validation.resend_confirmation') }}">Resend</a>.
    </p>
  </div>
</body>

{% endblock %}

templates/validation/informationUserValidate.html
{% extends "_base.html" %}

{% block content %}

<body class="body_login">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <main class="form-signin w-100 m-auto">
                <form role="form" method="post" action="">
                    {{ form.csrf_token }}
                    <h1 class="h3 mb-3 fw-normal text-center">USER INFORMATION </h1>
                    <div class="form-floating" style="border-radius: 20px;">
                        {{ form.Fullname(placeholder="Fullname", class="form-control mb-2") }}
                        {{ form.Fullname.label }}
                        {% if form.Fullname.errors %}
                            {% for error in form.Fullname.errors %}
                                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-floating" style="border-radius: 20px;">
                        {{ form.Nickname(placeholder="Nickname", class="form-control mb-2") }}
                        {{ form.Nickname.label }}
                        {% if form.Nickname.errors %}
                            {% for error in form.Nickname.errors %}
                                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                    {{ error }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    {% if current_user.authenticated_by != "google" %}
                        <div class="form-floating" style="border-radius: 20px;">
                            {{ form.Email(placeholder="Email", class="form-control mb-2") }}
                            {{ form.Email.label }}
                            {% if form.Email.errors%}
                                {% for error in form.Email.errors %}
                                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                        {{ error }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                            aria-label="Close"></button>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endif %}
                    <div class="form-floating" style="border-radius: 20px;">
                        {{ form.Contactaddress(placeholder="Contact address", class="form-control mb-2") }}
                        {{ form.Contactaddress.label }}
                        {% if form.Contactaddress.errors %}
                            {% for error in form.Contactaddress.errors %}
                                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                    {{ error }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <button class="button login__submit" type="submit" style="background-color:rgb(181, 181, 244);">
                        <span class="button__text">SIGN IN</span>
                        <i class="button__icon fas fa-chevron-right" style="color:rgb(224, 18, 52)"></i>
                    </button>
                </form>
            </main>
        </div>
        <div class="col-md-4"></div>
    </div>

</body>

{% endblock %}